### ISSUE TITLE
md5() expects parameter 1 to be string, resource given

### ISSUE THREAD

**Issue by tchapi** [sabre-io/dav#1199]
Hello

When trying to upload an `invite.ics` file to `/dav.php/calendars/myuser/inbox/`, I have an error :

    4.0.1
    TypeError
    md5() expects parameter 1 to be string, resource given

It seems to come from the fact that the PDO backend tries to compute the md5 of a resource, not a string, and thus fails when inserting the object in the database.

I'm trying to insert a scheduling object (an attendee reply) so that the original event is updated.

```
TypeError: md5() expects parameter 1 to be string, resource given in /var/www/calendar_server/vendor/sabre/dav/lib/CalDAV/Backend/PDO.php:1296"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "Stack trace:"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#0 /var/www/calendar_server/vendor/sabre/dav/lib/CalDAV/Backend/PDO.php(1296): md5(Resource id #81)"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#1 /var/www/calendar_server/vendor/sabre/dav/lib/CalDAV/Schedule/Inbox.php(107): Sabre\CalDAV\Backend\PDO->createSchedulingObject('principals/myuser...', 'test.ics', Resource id #81)"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#2 /var/www/calendar_server/vendor/sabre/dav/lib/DAV/Server.php(1094): Sabre\CalDAV\Schedule\Inbox->createFile('test.ics', Resource id #81)"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#3 /var/www/calendar_server/vendor/sabre/dav/lib/DAV/CorePlugin.php(527): Sabre\DAV\Server->createFile('calendars/myuser...', Resource id #81, NULL)"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#4 /var/www/calendar_server/vendor/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))"
[20-Oct-2019 16:29:54] WARNING: [pool www] child 411 said into stderr: "#5 /var/www/calendar_server/vendor/sabre/dav/lib/DAV/Server.php(464): Sabre\DAV\Server->emit('method:PUT',..."
```

Is this expected ? Am I doing something wrong ?

Thanks a lot !
BR

**Comment by alecpl** [comment]
Obviously a bug. `Inbox::createFile()` accepts data as a string or resource, but it looks like the `PDO::createSchedulingObject()` accepts only string.
