### ISSUE TITLE
email addresses should be compared case-insensitive

### ISSUE THREAD

**Issue by pk1234** [sabre-io/dav#1250]
Function Sabre\VObject\Property\ICalendar\CalAddress::getNormalizedValue() is called from:
- Sabre\VObject\ITip\Broker::parseEventInfo()
- Sabre\CalDAV\Schedule\Plugin::processICalendarChange()

Its purpose is to lowercase the schema in schema:value-hrefs. Therefore
- getNormalizedValue(MAILTO:user@domain.tld) === getNormalizedValue(mailto:user@domain.tld)

Sabre\VObject\ITip\Broker::parseEventInfo() uses this function to compare the email address of a principal with the email address of an attendee of a vevent. And in our setup this results in comparing mailto:User@domain.tld with mailto:user@domain.tld.
- getNormalizedValue(mailto:User@domain.tld) !== getNormalizedValue(mailto:user@domain.tld)

and therefor I believe that Sabre\VObject\Property\ICalendar\CalAddress::getNormalizedValue() should lowercase not only the schema but the complete address if the address is of type mailto:

So I replaced
```
    function getNormalizedValue() {

        $input = $this->getValue();
        if (!strpos($input, ':')) {
            return $input;
        }
        list($schema, $everythingElse) = explode(':', $input, 2);
        return strtolower($schema) . ':' . $everythingElse;
    }
```
by
```
    function getNormalizedValue() {

        $input = $this->getValue();
        if(!strncasecmp($input,"mailto:",7)) return strtolower($input);
        if (!strpos($input, ':')) {
            return $input;
        }
        list($schema, $everythingElse) = explode(':', $input, 2);
        return strtolower($schema) . ':' . $everythingElse;
    }
```
in file vendor/sabre/vobject/lib/Property/ICalendar/CalAddress.php

**Comment by staabm** [comment]
To me this sounds like a bug. Good find.

**Comment by staabm** [comment]
Are you willing to work on a fix and unit-tests?

**Comment by pk1234** [comment]
Sure - just give me a hint what I should do or point me at a document (or sample) that describes how to create a Sabre-php-unit-test

**Comment by phil-davis** [comment]
The code is in https://github.com/sabre-io/vobject so you need to change it there.
https://github.com/sabre-io/vobject/blob/master/lib/Property/ICalendar/CalAddress.php
and the tests:
https://github.com/sabre-io/vobject/blob/master/tests/VObject/Property/ICalendar/CalAddressTest.php

It should just need adding some extra "interesting" examples in the test data `public function values()` and then adjust the source code in `CalAddress.php` `getNormalizedValue()` to make the tests pass.

To run the tests, get in the repo root and:
```
composer install
composer phpunit
```

**Comment by phil-davis** [comment]
I see where the existing code is checking the organiser case-insensitive:
https://github.com/sabre-io/vobject/pull/435/files#diff-ec0db8ba5555c55504669c26fd107c5d
And that uppercase comparison should be OK.

But I don't see where the code is comparing the organiser and attendee.

**Comment by pk1234** [comment]
Have alook at #1249.
- function Sabre\VObject\ITip\Broker::parseEvent() is called with two calendar objects (parameters $calendar and $oldCalendar) and a list of addresses (parameter $userHref)
- parseEvent extracs (among other informations) the email addresses of the organizer and the attendees of both calendar objects and stores this information in $eventInfo and $oldEventInfo
- at a later point parseEvent checks whether the email-addresses from $eventInfo and $oldEventInfo are within the $userHref-Array. This is done with the in_array() function
- but `in_array($eventInfo['organizer'], $userHref)`is false when `$eventInfo['organizer']=="mailto:user@domain.tld"` and `$userHref==["mailto:User@domain.tld", "/dav/server.php/principals/user/"]`

Therefore I changed the getNormalizedValue()-function which is used when $eventInfo and $oldEventInfo are calculated with parseEventInfo(). Also I had to replace the elements of the $userHref array by their normalized values. To do this I replaced
```
$userHref = (array)$userHref;
```
by
```
$userHref = (array)$userHref;
foreach($userHref as &$h) if(!strncasecmp($h,"mailto:",7)) $h=strtolower($h);
unset($h);
```
at the beginning of parseEvent()

Of course I could replace the elements of $userHref as above and then do:
```
in_array(strtolower($eventInfo['organizer']), $userHref)
```
That way getNormalizedvalue() would need no changes at all.

Peter

**Comment by pk1234** [comment]
I will create a fix and write some unit-tests. But we are on SabreDAV-3.2.2 with php 5.6 and I will upgrade to php 7.4 / SabreDAV 4.0.3 first. This might take a while , so be patient.

**Comment by pk1234** [comment]
It took some time, but we finally migrated our SabreDAV server from 3.2.2 to 4.3.1.
And I just created my first sabre pull request https://github.com/sabre-io/vobject/pull/565 that fixes getNormalizeValue() and also adds some testcases to the corresponding unittest.

This does not fix the complete problem. Whenever attendee1 is compared with attendee2 the normalized value of attendee1 has to be compared with the normalized value of attendee2.

I fixed that in the 3.2.2 version of Sabre\VObject\ITip\Broker::parseEvent() and it will be easy to do the same with the 4.3.1 version. But I cannot figure out how to write testcases for this scenario?

With my current installation I can do:
```
/home/www/SabreDAV-4.3.1# vendor/bin/phpunit vendor/sabre/vobject/tests/VObject/Property/ICalendar
PHPUnit 9.5.14 by Sebastian Bergmann and contributors.
.........................................................         57 / 57 (100%)
Time: 00:00.066, Memory: 6.00 MB
OK (57 tests, 162 assertions)
```
but doing the same with the ITip unittests fails:
```
/home/www/SabreDAV-4.3.1# vendor/bin/phpunit vendor/sabre/vobject/tests/VObject/ITip
PHP Fatal error:  Uncaught Error: Class "Sabre\VObject\ITip\BrokerTester" not found in /home/www/SabreDAV-4.3.1/vendor/sabre/vobject/tests/VObject/ITip/BrokerAttendeeReplyTest.php:5
Stack trace:
#0 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once()
#1 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
#2 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/Framework/TestSuite.php(401): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/Framework/TestSuite.php(529): PHPUnit\Framework\TestSuite->addTestFile()
#4 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(98): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/TextUI/Command.php(120): PHPUnit\Runner\BaseTestRunner->getTest()
#6 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
#7 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#8 /home/www/SabreDAV-4.3.1/vendor/bin/phpunit(120): include('...')
#9 {main}
Next PHPUnit\TextUI\RuntimeException: Class "Sabre\VObject\ITip\BrokerTester" not found in /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/TextUI/Command.php:98
Stack trace:
#0 /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#1 /home/www/SabreDAV-4.3.1/vendor/bin/phpunit(120): include('...')
#2 {main}
  thrown in /home/www/SabreDAV-4.3.1/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98
```
Seems like I need some help with phpunit or autoloading

Peter
