### ISSUE TITLE
UnsupportedMediaType

### ISSUE THREAD

**Issue by Josch-** [sabre-io/dav#1268]
Hi,

I got lots of these lines in the error log:

`AH01071: Got error 'PHP message: Sabre\\DAV\\Exception\\UnsupportedMediaType: This resource only supports valid vCard or jCard data. Parse error: Invalid Mimedir file. Line starting at 11 did not follow iCalendar/vCard conventions in /var/www/vhosts/web1.server.de/httpdocs/baikal/vendor/sabre/dav/lib/CardDAV/Plugin.php:338\nStack trace:\n#0 /var/www/vhosts/web1.server.de/httpdocs/baikal/vendor/sabre/dav/lib/CardDAV/Plugin.php(303): Sabre\\CardDAV\\Plugin->validateVCard('BEGIN:VCARD\\r\\nVE...', false)\n#1 /var/www/vhosts/web1.server.de/httpdocs/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\\CardDAV\\Plugin->beforeCreateFile('addressbooks/ad...', 'BEGIN:VCARD\\r\\nVE...', Object(Sabre\\CardDAV\\AddressBook), false)\n#2 /var/www/vhosts/web1.server.de/httpdocs/baikal/vendor/sabre/dav/lib/DAV/Server.php(1090): Sabre\\DAV\\Server->emit('beforeCreateFil...', Array)\n#3 /var/www/vhosts/web1.server.de/httpdocs/baikal/vendor/sabre/dav/lib/DAV/CorePlugin.php(527): Sabre\\DAV\\Server->createFile('addressbooks/ad...', 'BEGIN:VCARD\\r\\nVE...'...'`

How can I find out, which cards cause this? Or isn't this the cause?

Thanks a lot in advance and best wishes,

Joska

**Comment by evert** [comment]
This has to be caught during the actual `PUT` request.  The card is unfortunately lost if you only have a log entry.
