### ISSUE TITLE
Permission denied to create file after upgrading from 0.4.6 to 0.6.1(0.7.1)

### ISSUE THREAD

**Issue by fanto666** [sabre-io/dav#1289]
**Baikal version**: 0.7.1

- [x] I have searched open and closed issues for duplicates
- [x] I have installed the release zip, not the source code zip
- [x] I have moved the whole, untouched `Specific` and `config` folders to the new installation

**Problem**:

we upgraded underlying OS from debian 8/php5.6  to debian 10 with php7.3
(we messed up the first time)
synchronization worked, admin login was impossible.

We tried upgrading to 0.7.1, replacing the directory with source content
(we know we messed up again). 

after upgrading from 0.4.6 to 0.6.1 we copied Spefic directory from original installation (config/ didn't exist yet)

we get  user reports synchronization does not work - new records can not be added.
outlook plugin reports errors, android reports synchronization OK, but no changes appear on server.

Problems persist after upgrading to 0.7.0/0.7.1

user sees in error log:
```
 Error while updating item: [redacted]. WebDav request failed: Status [Forbidden].
[<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.0.2</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>Permission denied to create file (filename
0f14715a-b924-45b6-a3d1-3e8d956f144d.vcf)</s:message>
</d:error>
]
```

we see in apache error log:

```
[Fri Jul 24 08:39:00.436836 2020] [php7:notice] [pid 27589] [client x.x.x.x:51992]
Sabre\\DAV\\Exception\\Forbidden: Permission denied to create file (filename 0f14715a-b924-45b6-a3d1-3e8d956f144d.vcf) in /var/www/html/baikal/vendor/sabre/dav/lib/DAV/Collection.php:92
Stack trace:
#0 /var/www/html/baikal/vendor/sabre/dav/lib/DAV/Server.php(1094): Sabre\\DAV\\Collection->createFile('0f14715a-b924-4...', Resource id sabre-io/Baikal#5)
sabre-io/Baikal#1 /var/www/html/baikal/vendor/sabre/dav/lib/DAV/CorePlugin.php(527): Sabre\\DAV\\Server->createFile('0f14715a-b924-4...', Resource id sabre-io/Baikal#5, NULL)
sabre-io/Baikal#2 /var/www/html/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(96): Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
sabre-io/Baikal#3 /var/www/html/baikal/vendor/sabre/dav/lib/DAV/Server.php(464): Sabre\\DAV\\Server->emit('method:PUT', Array)
sabre-io/Baikal#4 /var/www/html/baikal/vendor/sabre/dav/lib/DAV/Server.php(241): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
sabre-io/Baikal#5 /var/www/html/baikal/vendor/sabre/dav/lib/DAV/Server.php(309): Sabre\\DAV\\Server->start()
sabre-io/Baikal#6 /var/www/html/baikal/Core/Frameworks/Baikal/Core/Server.php(123): Sabre\\DAV\\Server->exec()
sabre-io/Baikal#7 /var/www/html/baikal/html/card.php(66): Baikal\\Core\\Server->start()
sabre-io/Baikal#8 {main}
```

**Comment by ByteHamster** [comment]
That sounds like a problem in `sabre/dav`, the actual server library. Baikal is only an admin interface for `sabre/dav`. I do not know enough about the library to help you but I have moved this issue to the `sabre/dav` repository. Maybe someone there can help you.
