### ISSUE TITLE
Newbie question: Sabre\DAV\Exception\NotImplemented

### ISSUE THREAD

**Issue by murraycollingwood** [sabre-io/dav#1346]
Have just upgraded from v2 to v3.2.2.
I am now using the composer installed version and have for the last few days been rewriting my integration.
Previously when I would send this request I would receive some calendar events, now it doesn't work and I'm not sure where else to look.
I am adding my URL to OSX Calendar application, as a new calendar subscription.
In Charles the request looks like this:

`GET /sabredav/server.php/principals/murray@gk=WzE2MjUyMTE1NjMsMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd/ HTTP/1.1
--
text/calendar
PHPSESSID=p712n7r0i4unsllgps963dc8qp
Mac+OS+X/10.15.7 (19H2) Calendar/2760.4.1
en-au
gzip, deflate
keep-alive
sobs`

The response is:
`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> 
	<s:sabredav-version>3.2.2</s:sabredav-version> 
	<s:exception>Sabre\DAV\Exception\NotImplemented</s:exception> 
	<s:message>There was no plugin in the system that was willing to handle this GET method. Enable the Browser plugin to get a better result here.</s:message> 
</d:error>`

By default I didn't include the browser plugin (it said it was optional).  If I include the browser plugin the response is a long HTML formatted display of my profile, permissions and other stuff, but there are no calendar events included.  

The OSX Calendar application is saying: An error occurred (with the browser plugin excluded).  Invalid response format (with the browser plugin included).

Any hints as to what I have done wrong???  

Thanks for your help
Murray

**Comment by murraycollingwood** [comment]
I'm happy to **PAY REAL MONEY** for somebody to help me get this working.

**Comment by murraycollingwood** [comment]
Is anybody reading this?  Is there anybody out there?

**Comment by murraycollingwood** [comment]
Hi Frzk

I would love to have the latest version, just not sure how to get to it.
I changed the version to "@stable" but nothing changes?
I then tried ">=4 @stable" and received the following response from composer:
```
  Problem 1
    - sabre/dav[4.0.0, ..., 4.1.5] require sabre/event ^5.0 -> found sabre/event[5.0.0, ..., 5.1.2] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires sabre/dav >=4 @stable -> satisfiable by sabre/dav[4.0.0, ..., 4.1.5].
```

And here is the main content of server.php
```
/* Database */
$pdo = Propel::getConnection();
$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
// Creating the backend.
$authBackend = new DAV\Auth\Backend\Sobsauth($pdo);
$principalBackend = new DAVACL\PrincipalBackend\Sobsprincipal($pdo);
$calendarBackend = new CalDAV\Backend\Sobscaldav($pdo);

// Directory tree
$tree = array(
    new DAVACL\PrincipalCollection($principalBackend),
    new CalDAV\CalendarRoot($principalBackend, $calendarBackend)
);  

// We're assuming that the realm name is called 'SabreDAV'.
$authBackend->setRealm('SabreDAV');


// The server object is responsible for making sense out of the WebDAV protocol
$server = new DAV\Server($tree);

// If your server is not on your webroot, make sure the following line has the
// correct information
$server->setBaseUri('/sabredav/server.php');

// Adding the plugin to the server.
// Creating the plugin.
$authPlugin = new DAV\Auth\Plugin($authBackend);
$server->addPlugin($authPlugin);

// CalDAV plugin
$caldavPlugin = new CalDAV\Plugin();
$server->addPlugin($caldavPlugin);

// CardDAV plugin
// $carddavPlugin = new CardDAV\Plugin();
// $server->addPlugin($carddavPlugin);

// ACL plugin
$aclPlugin = new DAVACL\Plugin();
$server->addPlugin($aclPlugin);

// Some logging of internal errors
$logger = new DAV\MockLogger();
$server->setLogger($logger);

// This ensures that we get a pretty index in the browser, but it is
// optional.
// $server->addPlugin(new DAV\Browser\Plugin());

// All we need to do now, is to fire up the server
$server->exec();
```

There is nothing special about the web server (apache2) config. 

BTW: Thanks for responding!

**Comment by Frzk** [comment]
Hi,

I guess `composer` refuses to proceed because you seem to have a "strong" dependency to `sabre/event` 3.0.0 (and the latest version of `sabre/DAV` requires `sabre/event` >=5.0.0.
Please check your `composer.json` file and then update your `composer.lock` file using `php composer.phar update` (which should also install everything needed).
If necessary, start reading from here: https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies :-)

Now, regarding your main issue, and since I don't see anything fancy in your `server.php`, I'm starting to wonder about the `murray@gk=WzE2MjUyMTE1NjMsMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd` part of the request, especially the part after `murray`. The `@` should be url encoded. And what's that cryptic string after ? Or is it added by Charles ?

So...what is your principal name ?
How did you setup your client ?
Have you tried to access the DAV server from a web browser, i.e. heading to `https://<EXAMPLE.COM>/sabredav/server.php/principals/<YOUR_PRINCIPAL>/` ?

**Comment by murraycollingwood** [comment]
I'm now at sabre/dav 4.1.5

Using Charles, the request is this:
```
GET /sabredav/server.php/principals/murray%40gk=WzE2MjY4MjI5OTUsMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd/ HTTP/1.1
Host: sobs
Accept: text/calendar
Cookie: PHPSESSID=56m90kfl65bj0pvdkn60qp6skr
User-Agent: Mac+OS+X/10.15.7 (19H2) Calendar/2760.4.1
Accept-Language: en-au
Accept-Encoding: gzip, deflate
Connection: keep-alive
```

And the response is:
```
HTTP/1.1 501 Not Implemented
Date: Tue, 20 Jul 2021 23:19:19 GMT
Server: Apache/2.4.41 (Unix) PHP/7.3.27
X-Powered-By: PHP/7.3.27
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Sabre-Version: 4.1.5
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.1.5</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this GET method. Enable the Browser plugin to get a better result here.</s:message>
</d:error>
```

I use <username>@<authentication-string> to get around the fact that Google and Microsoft don't provide any facility to automatically authenticate the user (ie that don't support a username and password with the request).   So I created a unique string with suitable security embedded that it will uniquely identify the user and is difficult to randomly generate.

My authentication plugin has a "check()" function, at the end of this function I generate a couple of log messages and return the authenticated principal:
```
        $authenticated = $this->principalPrefix . $username . "@gk=" . $currentuser->caldavUri3(true);
        
        trigger_error("SabreDAV: Authenticated $username @ " . $school->getName(), E_USER_NOTICE);
        trigger_error("SabreDAV: Authenticated " . $authenticated, E_USER_NOTICE);
        return array(true, $authenticated);
```


You can see the messages in my logging followed by the other error:
```
[32m[21-7-21 9:17am] [::1] SabreDAV: Authenticated murray @ Ronald St Home School[39m
[32m[21-7-21 9:17am] [::1] SabreDAV: Authenticated principals/murray@gk=WzE2MjY4MjMwNzksMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd[39m
[Wed Jul 21 09:17:59.541192 2021] [php7:notice] [pid 2867] [client ::1:49236] MOCK: level=error msg=Uncaught exception
[Wed Jul 21 09:17:59.541392 2021] [php7:notice] [pid 2867] [client ::1:49236]       Sabre\\DAV\\Exception\\NotImplemented: There was no plugin in the system that was willing to handle this GET method. Enable the Browser plugin to get a better result here. in /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php:479
[Wed Jul 21 09:17:59.541403 2021] [php7:notice] [pid 2867] [client ::1:49236]       Stack trace:
[Wed Jul 21 09:17:59.541410 2021] [php7:notice] [pid 2867] [client ::1:49236]       #0 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
[Wed Jul 21 09:17:59.541417 2021] [php7:notice] [pid 2867] [client ::1:49236]       #1 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\\DAV\\Server->start()
[Wed Jul 21 09:17:59.541424 2021] [php7:notice] [pid 2867] [client ::1:49236]       #2 /Users/murraycollingwood/dev/sobs-git/trunk/build/sabredav/server.php(77): Sabre\\DAV\\Server->exec()
[Wed Jul 21 09:17:59.541430 2021] [php7:notice] [pid 2867] [client ::1:49236]       #3 {main}
```

Does that help?

**Comment by DeepDiver1975** [comment]
> GET /sabredav/server.php/principals/murray%40gk=WzE2MjY4MjI5OTUsMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd/ HTTP/1.1
> Host: sobs
> Accept: text/calendar

you cannot get a calendar via this url

what client are you using?
did you read this? https://sabre.io/dav/building-a-caldav-client/

**Comment by murraycollingwood** [comment]
Is there any particular reason why I can't use this URL???
Previously I was using a URL like: /sabredav/server.php/principals/murray@schoolid=9223
This was working quite nicely with all my Apple devices, but only because Apple lets me enter a username and password for authentication with this URL.  (And it was on a version of SabreDAV that I had coded the plugin customisation directly into the library.  With the latest update (and now using Composer) I am attempting to implement the customisation external to the library so that it is easier to keep the library current.

The likes of Google and Microsoft don't have any option to record a username and password with the calendar URL, so I am left to my own design, so I designed a single URL that is appropriately secure and unique for each user. The URL is essentially self authenticating.

So again, why can't I use this URL?
I'm writing my own plugins to process the authentication and query my own database tables for the calendar events to be returned.

**Comment by Frzk** [comment]
Murray,

It's not that you can't use this URL.
The CalDAV plugin doesn't handle `GET` requests. That's why you get the `NotImplemented`.

Your client is sending a `GET` request to that specific URL (for some reason) and there is no plugin to answer this request.
That's also why you see a result when you enable the `Browser` plugin : this plugin handles `GET` request and thus responds to the request (yet the response doesn't seem to fit what your client is expecting).

**Comment by PHPGangsta** [comment]
> The likes of Google and Microsoft don't have any option to record a username and password with the calendar URL, so I am left to my own design, so I designed a single URL that is appropriately secure and unique for each user. The URL is essentially self authenticating.

@murraycollingwood What exactly do you want to do? Should Google have READ-ONLY access to your calendar? Or should Google have READ-WRITE access?

If you want to give a READ-ONLY URL to someone, there is an "ics Export" Plugin:
https://sabre.io/dav/ics-export-plugin/
With this you can download an .ics file with the calendar events in it. Maybe Google can use that and subscribe to that?

Then your only problem might be to disable the Authentication for that Plugin if Google connects to it... I would not use "a secret URL that nobody knows", URLs are stored in Browsers history, caches, are sent to "Google Safe Browsing", and so on... Keeping it secret is not so easy I guess... Maybe you can disable Authentication if the HTTP-Connection is coming from Googles "ICS Subscriber Bots" or so?

**Comment by murraycollingwood** [comment]
@PHPGangsta Yes, I have a READ-ONLY calendar of school events that staff need to be able to pull a personalised list of events down to their own calendar application.  For example a staff member using Outlook would add the calendar like this:
![image](https://user-images.githubusercontent.com/5810216/126489732-5d60bafe-4c82-44b4-88f3-f3dc7ef2c13d.png)

I'm assuming Outlook will send a GET request.

I will have a look at the ics-export-plugin.  I'm assuming it supports the GET request.

The URL I provide is similar to the one in the Microsoft example above.  It is never used in the address bar of the browser but entered directly into the calendar client application.  We warn the users that they should not post the URL to any social media or forums.

**Comment by murraycollingwood** [comment]
I've enabled the ICSExport plugin and added "?export" to my URL.

I'm now getting this error:
```
[Thu Jul 22 10:26:33.714162 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730] MOCK: level=info msg=Uncaught exception
[Thu Jul 22 10:26:33.714525 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       Sabre\\DAVACL\\Exception\\NeedPrivileges: User did not have the required privileges ({DAV:}read) for path "principals/murray@gk=WzE2MjY4MjI5OTUsMTYsMTUsIjgxZmFiZTYxNTNlMzE4NTYiLCJlV0Z5Y25WdCJd" in /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAVACL/Plugin.php:220
[Thu Jul 22 10:26:33.714613 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       Stack trace:
[Thu Jul 22 10:26:33.714656 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #0 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAVACL/Plugin.php(846): Sabre\\DAVACL\\Plugin->checkPrivileges('principals/murr...', Array)
[Thu Jul 22 10:26:33.714681 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #1 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
[Thu Jul 22 10:26:33.714702 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #2 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\\DAV\\Server->emit('beforeMethod:GE...', Array)
[Thu Jul 22 10:26:33.714719 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #3 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
[Thu Jul 22 10:26:33.714739 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #4 /Users/murraycollingwood/dev/sobs-git/trunk/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\\DAV\\Server->start()
[Thu Jul 22 10:26:33.714773 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #5 /Users/murraycollingwood/dev/sobs-git/trunk/build/sabredav/server.php(77): Sabre\\DAV\\Server->exec()
[Thu Jul 22 10:26:33.714802 2021] [php7:notice] [pid 452] [client 127.0.0.1:56730]       #6 {main}
```

**Comment by murraycollingwood** [comment]
@Frzk @DeepDiver1975 @PHPGangsta 
Any help on this latest error - where should I be specifying this read access?

My sobsprincipal.php is the ACL plugin and this returns the following:
```
		return array(
				'id' => $currentuser->getId(),
				'uri' => "principals/" . $currentuser->getUsername() .
						"@gk=" . $currentuser->caldavUri3(true),
                '{DAV:}displayname' => $currentuser->name(),
                '{http://sabredav.org/ns}email-address' => $currentuser->getEmail());
```

What am I missing?

**Comment by murraycollingwood** [comment]
My customers need me to support three companies, just three!  Apple, MS and Google.  These are the big three when it comes to providing calendar and scheduling support.
I implemented Sabredav to support CalDAV in my application and it has been working well for a number of years, but only with Apple.  Google and MS have not supported direct integration of CalDAV.

Instead Google and MS have implemented support for a subscription protocol that relies on a single URL to access a calendar and return events in an ical / ics format file.  Apple also support this subscription protocol.  Sabredav does not have any support for this subscription model.

Sadly we will be dropping support for CalDAV (and Sabredav) and pushing the subscription protocol model.
Thanks for your help over the years.  Wishing you well.
