### ISSUE TITLE
Error accessing DAV included in Afterlogic Webmail Pro installed on Plesk

### ISSUE THREAD

**Issue by Johnny99211** [sabre-io/dav#1369]
I need some help! I've installed the Afterlogic Webmail Pro on my Plesk system. Everything works - except DAV. When I'm trying to access the integrated DAV from sabre, I'm getting this error inside my logs after authentication:

```
d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>File not found: dav.php in 'root'</s:message>
<s:file>/var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/sabre-dav/lib/DAV/SimpleCollection.php</s:file>
<s:line>91</s:line>
<s:code>0</s:code>
<s:stacktrace>#0 /var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/sabre-dav/lib/DAV/Tree.php(68): Sabre\DAV\SimpleCollection->getChild('dav.php') #1 /var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/dav/lib/DAV/FS/Plugin.php(255): Sabre\DAV\Tree->getNodeForPath('dav.php') #2 [internal function]: Afterlogic\DAV\FS\Plugin->methodGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #3 /var/www/vhosts/test.de/mail.test.de/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array) #4 /var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/sabre-dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:GET', Array) #5 /var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/sabre-dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #6 /var/www/vhosts/test.de/mail.test.de/vendor/afterlogic/dav/lib/DAV/Server.php(270): Sabre\DAV\Server->exec() #7 /var/www/vhosts/test.de/mail.test.de/dav.php(28): Afterlogic\DAV\Server->exec() #8 {main}</s:stacktrace>
</d:error>
```

We require urgent help because we are a small company and things need to work to be successful.

**Comment by DeepDiver1975** [comment]
Please reach out to afterlogic to find our what is wrongly setup or configured in your system. THX
