### ISSUE TITLE
PHP 8.2 dynamic properties deprecation warnings

### ISSUE THREAD

**Issue by AaronVanGeffen** [sabre-io/dav#1445]
In PHP 8.2, dynamic class properties [have been deprecated](https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties). Apparently, Sabre\DAV still uses some in at least two locations, leading to errors below.

Baikal is working again after quickly patching the two classes. I do not currently have time to upstream my changes, but I thought I'd report these findings either way.

```
PHP message: ErrorException: Creation of dynamic property Sabre\DAV\Xml\Property\Href::$autoPrefix is deprecated in /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Backend/PDO.php:100
Stack trace:
#0 [internal function]: Baikal\Framework::exception_error_handler()
#1 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Backend/PDO.php(100): unserialize()
#2 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Plugin.php(84): Sabre\DAV\PropertyStorage\Backend\PDO->propFind()
#3 /usr/share/webapps/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\PropertyStorage\Plugin->propFind()
#4 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(1052): Sabre\DAV\Server->emit()
#5 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(984): Sabre\DAV\Server->getPropertiesByNode()
#6 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(1662): Sabre\DAV\Server->getPropertiesIteratorForPath()
#7 /usr/share/webapps/baikal/v
```

```
PHP message: ErrorException: Creation of dynamic property Sabre\CardDAV\Xml\Request\AddressBookMultiGetReport::$addressDataProperties is deprecated in /usr/share/webapps/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php:104
Stack trace:
#0 /usr/share/webapps/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php(104): Baikal\Framework::exception_error_handler()
#1 [internal function]: Sabre\CardDAV\Xml\Request\AddressBookMultiGetReport::xmlDeserialize()
#2 /usr/share/webapps/baikal/vendor/sabre/xml/lib/Reader.php(234): call_user_func()
#3 /usr/share/webapps/baikal/vendor/sabre/xml/lib/Reader.php(75): Sabre\Xml\Reader->parseCurrentElement()
#4 /usr/share/webapps/baikal/vendor/sabre/xml/lib/Service.php(129): Sabre\Xml\Reader->parse()
#5 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/CorePlugin.php(679): Sabre\Xml\Service->parse()
#6 /usr/share/webapps/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpReport()
```

**Comment by phil-davis** [comment]
PR #1446 fixes the `addressDataProperties` problem.

I don't see where the `autoPrefix` stuff happens any more. PR #801 looks like it removed that back in 2016.
Is there some remnant of it still in the code?
@DeepDiver1975 @staabm do you know anything about `autoPrefix` ?

**Comment by staabm** [comment]
> do you know anything about autoPrefix ?

Nope

**Comment by AaronVanGeffen** [comment]
> PR #1446 fixes the `addressDataProperties` problem.

Thanks. Good to hear.

> I don't see where the `autoPrefix` stuff happens any more. PR #801 looks like it removed that back in 2016. Is there some remnant of it still in the code?

Most likely. Baikal [still uses DAV 4.3.0](https://github.com/sabre-io/Baikal/blob/39882384483ef5a749ce403d9d167a5849d294ed/composer.json#L17), but that's new enough to include the changes from 2016.

**Comment by mokraemer** [comment]
Same issues here.
Maybe use https://github.com/phan/phan to ommit those errors

**Comment by murraycollingwood** [comment]
I've just upgraded to PHP 8.2 and getting these errors.
Currently I'm using "sabre/dav": "@stable"

Rather than fixing them directly, is there a composer version I can install?

Cheers
Murray

**Comment by DeepDiver1975** [comment]
Issues have been solve - new release will follow #1493

**Comment by AaronVanGeffen** [comment]
One of the two issues still remains:
```
2023/11/21 19:05:43 [error] 566#566: *20360 FastCGI sent in stderr:
"PHP message: ErrorException: Creation of dynamic property Sabre\DAV\Xml\Property\Href::$autoPrefix is deprecated in /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Backend/PDO.php:100
Stack trace:
#0 [internal function]: Baikal\Framework::exception_error_handler()
#1 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Backend/PDO.php(100): unserialize()
#2 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/PropertyStorage/Plugin.php(84): Sabre\DAV\PropertyStorage\Backend\PDO->propFind()
#3 /usr/share/webapps/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\PropertyStorage\Plugin->propFind()
#4 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(1052): Sabre\DAV\Server->emit()
#5 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(984): Sabre\DAV\Server->getPropertiesByNode()
#6 /usr/share/webapps/baikal/vendor/sabre/dav/lib/DAV/Server.php(1662): Sabre\DAV\Server->getPropertiesIteratorForPath()
#7 /usr/share/webapps/baikal/v" while reading response header from upstream
```

**Comment by mokraemer** [comment]
can you reopen this bug, or will you file a new one? if it is closed, I don't think they'll see the comments.

**Comment by DeepDiver1975** [comment]
We track this in the open Baikal issue.

**Comment by phil-davis** [comment]
Release https://github.com/sabre-io/dav/releases/tag/4.5.1 should have fixed the HRef autoPrefix problem.
