### ISSUE TITLE
500s from address book after upgrading to PHP 8.2

### ISSUE THREAD

**Issue by nekr0z** [sabre-io/dav#1474]
```
[php:notice] [pid 294513] [client <<REDACTED IPv6 HERE>>] ErrorException: Creation of dynamic property Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport::$addressDataProperties is deprecated in /home/evgeny/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php:104\nStack trace:\n#0 /home/evgeny/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php(104): Baikal\\Framework::exception_error_handler()\n#1 [internal function]: Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport::xmlDeserialize()\n#2 /home/evgeny/baikal/vendor/sabre/xml/lib/Reader.php(234): call_user_func()\n#3 /home/evgeny/baikal/vendor/sabre/xml/lib/Reader.php(75): Sabre\\Xml\\Reader->parseCurrentElement()\n#4 /home/evgeny/baikal/vendor/sabre/xml/lib/Service.php(129): Sabre\\Xml\\Reader->parse()\n#5 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/CorePlugin.php(679): Sabre\\Xml\\Service->parse()\n#6 /home/evgeny/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\\DAV\\CorePlugin->httpReport()\n#7 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\\DAV\\Server->emit()\n#8 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\\DAV\\Server->invokeMethod()\n#9 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\\DAV\\Server->start()\n#10 /home/evgeny/baikal/Core/Frameworks/Baikal/Core/Server.php(119): Sabre\\DAV\\Server->exec()\n#11 /home/evgeny/baikal/html/dav.php(69): Baikal\\Core\\Server->start()\n#12 {main}
```
all over the access.log, with the corresponding error.log:
```
"REPORT /dav.php/addressbooks/nekr0z/default/ HTTP/1.1" 500 762 "-" "vdirsyncer/0.19.0"
```

**Comment by nekr0z** [comment]
Looks like a duplicate of #1445  that can be fixed with #1446
